# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c536ea2e20c800150328eb509d6a93088587a319e827cfdd91b1e93674977bc057e96172da74bbbd51a570ed80601961026c1bff941fd151c828e06cdb6f9820

test:
  secret_key_base: 320749a1f6ada2a4b83363a8bdbd4f04fa1cf5ba6ec0f6e12f14666fd3821ab1c8a9f31d8e07cdbf774b276e1aa6b6a3709818a2463df6245f75c0f0f7eb5218

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
